name: publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install xmllint and zip
        run: sudo apt-get -y install libxml2-utils zip
      - name: Build
        uses: qcastel/github-actions-maven-cmd@master
        with:
          maven-args: "clean install -DskipTests"
      - name: Build
        run: source .github/package.sh
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: releases/jose-cli-*.zip
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true